# This workflow creates the docker containers
# and runs tests

name: Runs tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating environment file
        run: cp example.env .env

      - name: Start containers
        run: docker-compose -f docker-compose.tests.yml up -d --build

      - name: Run tests
        run: docker-compose -f docker-compose.tests.yml run audit-service bash -c "pytest -v"

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.tests.yml down
